export const NOM_LIST = [
  { code: 'NOM-001-STPS-2008', title: 'Edificios, locales, instalaciones y áreas en los centros de trabajo - Condiciones de seguridad.' },
  { code: 'NOM-002-STPS-2010', title: 'Condiciones de seguridad - Prevención y protección contra incendios en los centros de trabajo.' },
  { code: 'NOM-004-STPS-1999', title: 'Sistemas de protección y dispositivos de seguridad en la maquinaria y equipo que se utilice en los centros de trabajo.' },
  { code: 'NOM-005-STPS-1998', title: 'Relativa a las condiciones de seguridad e higiene en los centros de trabajo para el manejo, transporte y almacenamiento de sustancias químicas peligrosas.' },
  { code: 'NOM-006-STPS-2014', title: 'Manejo y almacenamiento de materiales - Condiciones de seguridad y salud en el trabajo.' },
  { code: 'NOM-009-STPS-2011', title: 'Condiciones de seguridad para realizar trabajos en altura.' },
  { code: 'NOM-010-STPS-2014', title: 'Agentes químicos contaminantes del ambiente laboral - Reconocimiento, evaluación y control.' },
  { code: 'NOM-011-STPS-2001', title: 'Condiciones de seguridad e higiene en los centros de trabajo donde se genere ruido.' },
  { code: 'NOM-015-STPS-2001', title: 'Condiciones térmicas elevadas o abatidas - Condiciones de seguridad e higiene.' },
  { code: 'NOM-017-STPS-2008', title: 'Equipo de protección personal - Selección, uso y manejo en los centros de trabajo.' },
  { code: 'NOM-018-STPS-2015', title: 'Sistema armonizado para la identificación y comunicación de peligros y riesgos por sustancias químicas peligrosas en los centros de trabajo.' },
  { code: 'NOM-019-STPS-2011', title: 'Constitución, integración, organización y funcionamiento de las comisiones de seguridad e higiene.' },
  { code: 'NOM-020-STPS-2011', title: 'Recipientes sujetos a presión, recipientes criogénicos y generadores de vapor o calderas - Funcionamiento - Condiciones de seguridad.' },
  { code: 'NOM-022-STPS-2015', title: 'Electricidad estática en los centros de trabajo - Condiciones de seguridad.' },
  { code: 'NOM-025-STPS-2008', title: 'Condiciones de iluminación en los centros de trabajo.' },
  { code: 'NOM-026-STPS-2008', title: 'Colores y señales de seguridad e higiene, e identificación de riesgos por fluidos conducidos en tuberías.' },
  { code: 'NOM-027-STPS-2008', title: 'Actividades de soldadura y corte - Condiciones de seguridad e higiene.' },
  { code: 'NOM-029-STPS-2011', title: 'Mantenimiento de las instalaciones eléctricas en los centros de trabajo - Condiciones de seguridad.' },
  { code: 'NOM-030-STPS-2009', title: 'Funciones y actividades de los servicios preventivos de seguridad y salud en el trabajo - Funciones y actividades.' },
  { code: 'NOM-033-STPS-2015', title: 'Condiciones de seguridad para realizar trabajos en espacios confinados.' },
  { code: 'NOM-034-STPS-2016', title: 'Condiciones de seguridad para el acceso y desarrollo de actividades de trabajadores con discapacidad en los centros de trabajo.' },
  { code: 'NOM-035-STPS-2018', title: 'Factores de riesgo psicosocial en el trabajo - Identificación, análisis y prevención.' },
  { code: 'NOM-036-1-STPS-2018', title: 'Factores de riesgo ergonómico en el Trabajo - Identificación, análisis, prevención y control. Parte 1: Manejo manual de cargas.' },
];
